spring:
  application:
    name: miao-heritage-platform
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/miao_heritage?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # 开发阶段使用update，生产环境使用validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false # 开发阶段先关闭
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth/realms/miao-heritage}
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

# 区块链配置
fabric:
  network-config-path: ${FABRIC_CONFIG_PATH:classpath:hyperledger-fabric-network.json}
  channel-name: ${FABRIC_CHANNEL_NAME:miaoheritage}
  chaincode-name: ${FABRIC_CHAINCODE_NAME:miaoasset}
  wallet-directory: ${FABRIC_WALLET_PATH:wallet}
  organization: ${FABRIC_ORG:MiaoHeritageOrg}
  user-name: ${FABRIC_USER:Admin}

# 文件存储配置
file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads}
  max-size: 10MB
  allowed-types: jpg,jpeg,png,pdf

# 二维码配置
qrcode:
  width: 300
  height: 300
  format: PNG
  trace-url: ${TRACE_URL:https://miao-heritage.com/trace/}

# JWT配置
jwt:
  secret: ${JWT_SECRET:miaoHeritageSecretKeyForJwtAuthenticationAndBlockchainSecurity12345}
  expiration-ms: 86400000 # 24小时

# 支付配置
payment:
  # 回调接口
  notify-url: ${PAYMENT_NOTIFY_URL:http://localhost:8080/api/payment/notify}
  return-url: ${PAYMENT_RETURN_URL:http://localhost:8080/api/payment/return}
  
  # 支付宝配置
  alipay:
    app-id: ${ALIPAY_APP_ID:2021000000000000} # 示例ID，实际使用时替换
    private-key: ${ALIPAY_PRIVATE_KEY:your-private-key}
    public-key: ${ALIPAY_PUBLIC_KEY:your-public-key}
    gateway-url: ${ALIPAY_GATEWAY_URL:https://openapi.alipaydev.com/gateway.do} # 开发环境网关
  
  # 微信支付配置
  wechat:
    app-id: ${WECHAT_APP_ID:wx0000000000000000} # 示例ID，实际使用时替换
    mch-id: ${WECHAT_MCH_ID:1900000000} # 示例商户号，实际使用时替换
    api-key: ${WECHAT_API_KEY:your-api-key}
    api-v3-key: ${WECHAT_API_V3_KEY:your-api-v3-key}
    merchant-serial-number: ${WECHAT_MERCHANT_SERIAL_NUMBER:merchant-serial-number}
    private-key-path: ${WECHAT_PRIVATE_KEY_PATH:classpath:cert/wechatpay/apiclient_key.pem}
    api-url: ${WECHAT_API_URL:https://api.mch.weixin.qq.com} 

# AI配置
ai:
  deepseek:
    api-key: ${DEEPSEEK_API_KEY:your-api-key}
    vision-api-url: ${DEEPSEEK_VISION_API_URL:https://api.deepseek.com/v1/vision}
    llm-api-url: ${DEEPSEEK_LLM_API_URL:https://api.deepseek.com/v1/chat/completions}
  
  # 异步任务配置
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    thread-name-prefix: ai-task- 